version: "3.8"
services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  chatbot:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - DB_NAME=icare
      - JOURS_SEUIL=2
    ports:
      - "8000:8000"
    depends_on:
      - mongo
volumes:
  mongo-data:
